/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellIndexRouteImport } from './routes/_shell.index'
import { Route as ShellSettingsRouteImport } from './routes/_shell.settings'
import { Route as ShellPipelinesRouteImport } from './routes/_shell.pipelines'
import { Route as ShellBuildsRouteImport } from './routes/_shell.builds'
import { Route as ShellArtifactsRouteImport } from './routes/_shell.artifacts'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSettingsRoute = ShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPipelinesRoute = ShellPipelinesRouteImport.update({
  id: '/pipelines',
  path: '/pipelines',
  getParentRoute: () => ShellRoute,
} as any)
const ShellBuildsRoute = ShellBuildsRouteImport.update({
  id: '/builds',
  path: '/builds',
  getParentRoute: () => ShellRoute,
} as any)
const ShellArtifactsRoute = ShellArtifactsRouteImport.update({
  id: '/artifacts',
  path: '/artifacts',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/artifacts': typeof ShellArtifactsRoute
  '/builds': typeof ShellBuildsRoute
  '/pipelines': typeof ShellPipelinesRoute
  '/settings': typeof ShellSettingsRoute
}
export interface FileRoutesByTo {
  '/artifacts': typeof ShellArtifactsRoute
  '/builds': typeof ShellBuildsRoute
  '/pipelines': typeof ShellPipelinesRoute
  '/settings': typeof ShellSettingsRoute
  '/': typeof ShellIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/_shell/artifacts': typeof ShellArtifactsRoute
  '/_shell/builds': typeof ShellBuildsRoute
  '/_shell/pipelines': typeof ShellPipelinesRoute
  '/_shell/settings': typeof ShellSettingsRoute
  '/_shell/': typeof ShellIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/artifacts' | '/builds' | '/pipelines' | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to: '/artifacts' | '/builds' | '/pipelines' | '/settings' | '/'
  id:
    | '__root__'
    | '/_shell'
    | '/_shell/artifacts'
    | '/_shell/builds'
    | '/_shell/pipelines'
    | '/_shell/settings'
    | '/_shell/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings': {
      id: '/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ShellSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/pipelines': {
      id: '/_shell/pipelines'
      path: '/pipelines'
      fullPath: '/pipelines'
      preLoaderRoute: typeof ShellPipelinesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/builds': {
      id: '/_shell/builds'
      path: '/builds'
      fullPath: '/builds'
      preLoaderRoute: typeof ShellBuildsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/artifacts': {
      id: '/_shell/artifacts'
      path: '/artifacts'
      fullPath: '/artifacts'
      preLoaderRoute: typeof ShellArtifactsRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellArtifactsRoute: typeof ShellArtifactsRoute
  ShellBuildsRoute: typeof ShellBuildsRoute
  ShellPipelinesRoute: typeof ShellPipelinesRoute
  ShellSettingsRoute: typeof ShellSettingsRoute
  ShellIndexRoute: typeof ShellIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellArtifactsRoute: ShellArtifactsRoute,
  ShellBuildsRoute: ShellBuildsRoute,
  ShellPipelinesRoute: ShellPipelinesRoute,
  ShellSettingsRoute: ShellSettingsRoute,
  ShellIndexRoute: ShellIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
